# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
import img_rc
import sys
import time

#functions

def open_Ui_Acceuil():
    global Acceuil , ui
    Accueil = QtWidgets.QMainWindow()
    ui = Ui_Accueil()
    ui.setupUi(Accueil)
    Accueil.show()

def open_Ui_Consultation():
    global Consultation , ui
    Consultation = QtWidgets.QMainWindow()
    ui = Ui_Consultation()
    ui.setupUi(Consultation)
    Consultation.show()

def open_Ui_inscrit():
    global inscrit , ui
    Inscrit = QtWidgets.QMainWindow()
    ui = Ui_Inscrit()
    ui.setupUi(Inscrit)
    Inscrit.show()

def open_Ui_Incrpatient():
    global Incrpatient , ui
    Incrpatient = QtWidgets.QMainWindow()
    ui = Ui_Incrpatient()
    ui.setupUi(Incrpatient)
    Incrpatient.show()

def open_Dialog():
    global Dialog , ui
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()

def open_Ui_liste():
    global liste , ui
    liste = QtWidgets.QMainWindow()
    ui = Ui_liste()
    ui.setupUi(liste)
    liste.show()

def open_Ui_Loging():
    global Loging , ui
    Loging = QtWidgets.QMainWindow()
    ui = Ui_Loging()
    ui.setupUi(Loging)
    Loging.show()
    for i in range(1, 999):
        ui.progressBar.setValue(i)
        t = time.time()
        while time.time() < t + 0.009:
           app.processEvents()
    ui.suivant()

def open_Ui_Modif():
    global Modif, ui
    Modif = QtWidgets.QMainWindow()
    ui = Ui_Modif()
    ui.setupUi(Modif)
    Modif.show()

def open_Ui_Login():
    global Login, ui
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()

def open_Ui_Supression(arg):
    global Suppression, ui
    Suppression = QtWidgets.QMainWindow()
    ui = Ui_Suppression()
    ui.setupUi(Suppression)
    Suppression.show()

#functions

#Classes-----------------------------------------Classes

#Fenêtre Acceuil
class Ui_Accueil(object):
    def setupUi(self, Accueil):
        Accueil.setObjectName("Accueil")
        Accueil.resize(691, 489)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        Accueil.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Accueil)
        self.centralwidget.setObjectName("centralwidget")
        self.acceul = QtWidgets.QLabel(self.centralwidget)
        self.acceul.setGeometry(QtCore.QRect(220, 80, 241, 41))
        self.acceul.setObjectName("acceul")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 220, 131, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 220, 131, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 160, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        Accueil.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Accueil)
        self.statusbar.setObjectName("statusbar")
        Accueil.setStatusBar(self.statusbar)
        self.actionenregistre = QtWidgets.QAction(Accueil)
        self.actionenregistre.setObjectName("actionenregistre")
        self.actionquitter = QtWidgets.QAction(Accueil)
        self.actionquitter.setObjectName("actionquitter")
        self.actionouvrire = QtWidgets.QAction(Accueil)
        self.actionouvrire.setObjectName("actionouvrire")

        self.retranslateUi(Accueil)
        QtCore.QMetaObject.connectSlotsByName(Accueil)

    def retranslateUi(self, Accueil):
        _translate = QtCore.QCoreApplication.translate
        Accueil.setWindowTitle(_translate("Accueil", "MainWindow"))
        self.acceul.setText(_translate("Accueil", "ACCEUIL"))
        self.pushButton.setText(_translate("Accueil", "consultation"))
        self.pushButton_2.setText(_translate("Accueil", "rendez-vous"))
        self.label_2.setText(_translate("Accueil", "bonjour Mr ou Mme vous êtes venus pour ?"))
        self.actionenregistre.setText(_translate("Accueil", "enregistre"))
        self.actionenregistre.setShortcut(_translate("Accueil", "Ctrl+S"))
        self.actionquitter.setText(_translate("Accueil", "quitter"))
        self.actionouvrire.setText(_translate("Accueil", "ouvrire"))
        self.actionouvrire.setShortcut(_translate("Accueil", "Ctrl+O"))

#Fenêtre CONSULTATION
class Ui_Consultation(object):
    def setupUi(self, Consultation):
        Consultation.setObjectName("Consultation")
        Consultation.resize(651, 337)
        self.centralwidget = QtWidgets.QWidget(Consultation)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 60, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(140, 190, 131, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 190, 131, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 130, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        Consultation.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Consultation)
        self.statusbar.setObjectName("statusbar")
        Consultation.setStatusBar(self.statusbar)

        self.retranslateUi(Consultation)
        QtCore.QMetaObject.connectSlotsByName(Consultation)

    def retranslateUi(self, Consultation):
        _translate = QtCore.QCoreApplication.translate
        Consultation.setWindowTitle(_translate("Consultation", "MainWindow"))
        self.label.setText(_translate("Consultation", "CONSULTATION"))
        self.pushButton.setText(_translate("Consultation", "NOUVEAU"))
        self.pushButton_2.setText(_translate("Consultation", "ANCIEN"))
        self.label_2.setText(_translate("Consultation", "êtes vous nouveau ou ancien?"))

#Fenêtre inscription
class Ui_Inscrit(object):
    def setupUi(self, Inscrit):
        Inscrit.setObjectName("Inscrit")
        Inscrit.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Inscrit)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 50, 651, 501))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QLineEdit{\n""    color: rgb(239, 239, 239);\n""    color: rgb(238, 238, 238);\n""background-color: rgb(188, 188, 188);\n""}")
        self.groupBox.setObjectName("groupBox")
        self.photo = QtWidgets.QLabel(self.groupBox)
        self.photo.setGeometry(QtCore.QRect(540, 10, 101, 101))
        self.photo.setStyleSheet("\n""background-color: rgb(203, 203, 203);")
        self.photo.setObjectName("photo")
        self.prenomClient = QtWidgets.QLineEdit(self.groupBox)
        self.prenomClient.setGeometry(QtCore.QRect(410, 180, 141, 21))
        self.prenomClient.setStyleSheet("border-color:black;\n""border-radius:10px;\n""border-style:solid;\n""border-width:1px;\n""")
        self.prenomClient.setObjectName("prenomClient")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 180, 31, 16))
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(340, 230, 31, 16))
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(330, 180, 47, 13))
        self.label_4.setObjectName("label_4")
        self.nomClient = QtWidgets.QLineEdit(self.groupBox)
        self.nomClient.setGeometry(QtCore.QRect(120, 180, 131, 21))
        self.nomClient.setStyleSheet("border-color:black;\n""border-radius:10px;\n""border-style:solid;\n""border-width:1px;\n""")
        self.nomClient.setText("")
        self.nomClient.setObjectName("nomClient")
        self.tool = QtWidgets.QToolButton(self.groupBox)
        self.tool.setGeometry(QtCore.QRect(620, 120, 25, 19))
        self.tool.setObjectName("tool")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(560, 120, 61, 16))
        self.label_13.setObjectName("label_13")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(310, 270, 91, 16))
        self.label_5.setObjectName("label_5")
        self.date = QtWidgets.QDateEdit(self.groupBox)
        self.date.setGeometry(QtCore.QRect(440, 270, 81, 22))
        self.date.setCalendarPopup(True)
        self.date.setObjectName("date")
        self.prof = QtWidgets.QLineEdit(self.groupBox)
        self.prof.setGeometry(QtCore.QRect(120, 220, 131, 21))
        self.prof.setStyleSheet("border-color:black;\n""border-radius:10px;\n""border-style:solid;\n""border-width:1px;\n""")
        self.prof.setObjectName("prof")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 280, 61, 16))
        self.label_10.setObjectName("label_10")
        self.nation = QtWidgets.QLineEdit(self.groupBox)
        self.nation.setGeometry(QtCore.QRect(120, 280, 131, 21))
        self.nation.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.nation.setStyleSheet("border-color:black;\n""border-radius:10px;\n""border-style:solid;\n""border-width:1px;\n""")
        self.nation.setObjectName("nation")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 220, 61, 16))
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 330, 47, 13))
        self.label_8.setObjectName("label_8")
        self.cni_Client = QtWidgets.QLineEdit(self.groupBox)
        self.cni_Client.setGeometry(QtCore.QRect(420, 310, 131, 21))
        self.cni_Client.setStyleSheet("border-color:black;\n""border-radius:10px;\n""border-style:solid;\n""border-width:1px;\n""")
        self.cni_Client.setObjectName("cni_Client")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(310, 310, 71, 16))
        self.label_11.setObjectName("label_11")
        self.cont = QtWidgets.QLineEdit(self.groupBox)
        self.cont.setGeometry(QtCore.QRect(120, 320, 141, 21))
        self.cont.setStyleSheet("border-color:black;\n""border-radius:10px;\n""border-style:solid;\n""border-width:1px;\n""")
        self.cont.setObjectName("cont")
        self.mail = QtWidgets.QLineEdit(self.groupBox)
        self.mail.setGeometry(QtCore.QRect(120, 360, 131, 21))
        self.mail.setStyleSheet("border-color:black;\n""border-radius:10px;\n""border-style:solid;\n""border-width:1px;\n""")
        self.mail.setObjectName("mail")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(30, 370, 41, 16))
        self.label_12.setObjectName("label_12")
        self.ann = QtWidgets.QPushButton(self.groupBox)
        self.ann.setGeometry(QtCore.QRect(190, 450, 81, 23))
        self.ann.setObjectName("ann")
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setGeometry(QtCore.QRect(310, 450, 20, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.save = QtWidgets.QPushButton(self.groupBox)
        self.save.setGeometry(QtCore.QRect(370, 450, 91, 23))
        self.save.setObjectName("save")
        self.sexe = QtWidgets.QComboBox(self.groupBox)
        self.sexe.setGeometry(QtCore.QRect(420, 230, 131, 22))
        self.sexe.setStyleSheet("border-color:black;\n""border-radius:10px;\n""border-style:solid;\n""border-width:1px;\n""")
        self.sexe.setObjectName("sexe")
        self.sexe.addItem("")
        self.sexe.setItemText(0, "")
        self.sexe.addItem("")
        self.sexe.addItem("")
        self.sexe_3 = QtWidgets.QComboBox(self.groupBox)
        self.sexe_3.setGeometry(QtCore.QRect(430, 370, 131, 22))
        self.sexe_3.setStyleSheet("border-color:black;\n""border-radius:10px;\n""border-style:solid;\n""border-width:1px;\n""")
        self.sexe_3.setObjectName("sexe_3")
        self.sexe_3.addItem("")
        self.sexe_3.setItemText(0, "")
        self.sexe_3.addItem("")
        self.sexe_3.addItem("")
        self.sexe_3.addItem("")
        self.sexe_3.addItem("")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(340, 370, 61, 16))
        self.label.setObjectName("label")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(60, 10, 121, 31))
        self.label_15.setStyleSheet("\n""color: rgb(170, 0, 0);")
        self.label_15.setObjectName("label_15")
        Inscrit.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Inscrit)
        self.statusbar.setObjectName("statusbar")
        Inscrit.setStatusBar(self.statusbar)

        self.retranslateUi(Inscrit)
        QtCore.QMetaObject.connectSlotsByName(Inscrit)

    def retranslateUi(self, Inscrit):
        _translate = QtCore.QCoreApplication.translate
        Inscrit.setWindowTitle(_translate("Inscrit", "MainWindow"))
        self.groupBox.setTitle(_translate("Inscrit", "OUVERTURE DE COMPTE"))
        self.photo.setText(_translate("Inscrit", "<html><head/><body><p align=\"center\">photo</p></body></html>"))
        self.label_3.setText(_translate("Inscrit", "Nom:"))
        self.label_7.setText(_translate("Inscrit", "Sexe:"))
        self.label_4.setText(_translate("Inscrit", "Prénom:"))
        self.tool.setText(_translate("Inscrit", "..."))
        self.label_13.setText(_translate("Inscrit", "<html><head/><body><p><span style=\" font-weight:600;\">Parcourir:</span></p></body></html>"))
        self.label_5.setText(_translate("Inscrit", "Date de naissance:"))
        self.label_10.setText(_translate("Inscrit", "Nationalité:"))
        self.nation.setPlaceholderText(_translate("Inscrit", "ivoirienne"))
        self.label_9.setText(_translate("Inscrit", "Profession:"))
        self.label_8.setText(_translate("Inscrit", "Contact:"))
        self.cni_Client.setPlaceholderText(_translate("Inscrit", "CI"))
        self.label_11.setText(_translate("Inscrit", "N° de la CNI:"))
        self.cont.setPlaceholderText(_translate("Inscrit", "+225"))
        self.label_12.setText(_translate("Inscrit", "E-mail:"))
        self.ann.setText(_translate("Inscrit", "ANNULER"))
        self.save.setText(_translate("Inscrit", "ENREGISTRER"))
        self.sexe.setItemText(1, _translate("Inscrit", "HOMME"))
        self.sexe.setItemText(2, _translate("Inscrit", "FEMME"))
        self.sexe_3.setItemText(1, _translate("Inscrit", "axa"))
        self.sexe_3.setItemText(2, _translate("Inscrit", "assurace"))
        self.sexe_3.setItemText(3, _translate("Inscrit", "mugefci"))
        self.sexe_3.setItemText(4, _translate("Inscrit", "dangereux "))
        self.label.setText(_translate("Inscrit", "assurance:"))
        self.label_15.setText(_translate("Inscrit", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">santé +</span></p><p align=\"center\"><br/></p></body></html>"))

#fenetre inscrpatient
class Ui_Incrpatient(object):
    def setupUi(self, Incrpatient):
        Incrpatient.setObjectName("Incrpatient")
        Incrpatient.resize(800, 651)
        self.centralwidget = QtWidgets.QWidget(Incrpatient)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QLineEdit{\n""    color: rgb(239, 239, 239);\n""    color: rgb(238, 238, 238);\n""background-color: rgb(188, 188, 188);\n""}")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sexe = QtWidgets.QComboBox(self.groupBox)
        self.sexe.setStyleSheet("border-color:black;\n""border-radius:10px;\n""border-style:solid;\n""border-width:1px;\n""")
        self.sexe.setObjectName("sexe")
        self.sexe.addItem("")
        self.sexe.setItemText(0, "")
        self.sexe.addItem("")
        self.sexe.addItem("")
        self.horizontalLayout_2.addWidget(self.sexe)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.date = QtWidgets.QDateEdit(self.groupBox)
        self.date.setCalendarPopup(True)
        self.date.setObjectName("date")
        self.horizontalLayout_3.addWidget(self.date)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 1, 1, 1)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem3)
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_27.addWidget(self.line_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_27, 8, 1, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tool = QtWidgets.QToolButton(self.groupBox)
        self.tool.setObjectName("tool")
        self.horizontalLayout.addWidget(self.tool)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 5, 1, 1)
        self.photo = QtWidgets.QLabel(self.groupBox)
        self.photo.setStyleSheet("\n""background-color: rgb(203, 203, 203);")
        self.photo.setObjectName("photo")
        self.gridLayout.addWidget(self.photo, 0, 4, 1, 2)
        self.cont_5 = QtWidgets.QLineEdit(self.groupBox)
        self.cont_5.setStyleSheet("border-color:black;\n""border-radius:10px;\n""border-style:solid;\n""border-width:1px;\n""")
        self.cont_5.setObjectName("cont_5")
        self.gridLayout.addWidget(self.cont_5, 3, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.prenomClient_5 = QtWidgets.QLineEdit(self.groupBox)
        self.prenomClient_5.setStyleSheet("border-color:black;\n""border-radius:10px;\n""border-style:solid;\n""border-width:1px;\n""")
        self.prenomClient_5.setObjectName("prenomClient_5")
        self.gridLayout.addWidget(self.prenomClient_5, 2, 3, 1, 1)
        self.lieu = QtWidgets.QLineEdit(self.groupBox)
        self.lieu.setStyleSheet("border-color:black;\n""border-radius:10px;\n""border-style:solid;\n""border-width:1px;\n""")
        self.lieu.setObjectName("lieu")
        self.gridLayout.addWidget(self.lieu, 6, 1, 1, 1)
        self.cni_Client = QtWidgets.QLineEdit(self.groupBox)
        self.cni_Client.setStyleSheet("border-color:black;\n""border-radius:10px;\n""border-style:solid;\n""border-width:1px;\n""")
        self.cni_Client.setObjectName("cni_Client")
        self.gridLayout.addWidget(self.cni_Client, 7, 1, 1, 1)
        self.nation = QtWidgets.QLineEdit(self.groupBox)
        self.nation.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.nation.setStyleSheet("border-color:black;\n""border-radius:10px;\n""border-style:solid;\n""border-width:1px;\n""")
        self.nation.setObjectName("nation")
        self.gridLayout.addWidget(self.nation, 6, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 7, 2, 1, 1)
        self.mail = QtWidgets.QLineEdit(self.groupBox)
        self.mail.setStyleSheet("border-color:black;\n""border-radius:10px;\n""border-style:solid;\n""border-width:1px;\n""")
        self.mail.setObjectName("mail")
        self.gridLayout.addWidget(self.mail, 7, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.groupBox)
        self.label_51.setObjectName("label_51")
        self.gridLayout.addWidget(self.label_51, 3, 2, 1, 1)
        self.nomClient = QtWidgets.QLineEdit(self.groupBox)
        self.nomClient.setStyleSheet("border-color:black;\n""border-radius:10px;\n""border-style:solid;\n""border-width:1px;\n""")
        self.nomClient.setText("")
        self.nomClient.setObjectName("nomClient")
        self.gridLayout.addWidget(self.nomClient, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.prof = QtWidgets.QLineEdit(self.groupBox)
        self.prof.setStyleSheet("border-color:black;\n""border-radius:10px;\n""border-style:solid;\n""border-width:1px;\n""")
        self.prof.setObjectName("prof")
        self.gridLayout.addWidget(self.prof, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 7, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 2, 1, 1)
        self.ann_2 = QtWidgets.QPushButton(self.groupBox)
        self.ann_2.setGeometry(QtCore.QRect(108, 428, 664, 23))
        self.ann_2.setObjectName("ann_2")
        self.save = QtWidgets.QPushButton(self.groupBox)
        self.save.setGeometry(QtCore.QRect(108, 457, 664, 23))
        self.save.setObjectName("save")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.groupBox)
        Incrpatient.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Incrpatient)
        self.statusbar.setObjectName("statusbar")
        Incrpatient.setStatusBar(self.statusbar)

        self.retranslateUi(Incrpatient)
        QtCore.QMetaObject.connectSlotsByName(Incrpatient)

    def retranslateUi(self, Incrpatient):
        _translate = QtCore.QCoreApplication.translate
        Incrpatient.setWindowTitle(_translate("Incrpatient", "MainWindow"))
        self.groupBox.setTitle(_translate("Incrpatient", "OUVERTURE DE COMPTE"))
        self.sexe.setItemText(1, _translate("Incrpatient", "HOMME"))
        self.sexe.setItemText(2, _translate("Incrpatient", "FEMME"))
        self.tool.setText(_translate("Incrpatient", "..."))
        self.photo.setText(_translate("Incrpatient", "<html><head/><body><p align=\"center\">photo</p></body></html>"))
        self.cont_5.setPlaceholderText(_translate("Incrpatient", "+225"))
        self.label_5.setText(_translate("Incrpatient", "Date de naissance:"))
        self.label_6.setText(_translate("Incrpatient", "<html><head/><body><p><span style=\" font-weight:600;\">A</span></p></body></html>"))
        self.label_13.setText(_translate("Incrpatient", "<html><head/><body><p><span style=\" font-weight:600;\">Parcourir:</span></p></body></html>"))
        self.label_3.setText(_translate("Incrpatient", "Nom:"))
        self.cni_Client.setPlaceholderText(_translate("Incrpatient", "CI"))
        self.nation.setPlaceholderText(_translate("Incrpatient", "ivoirienne"))
        self.label_12.setText(_translate("Incrpatient", "E-mail:"))
        self.label_7.setText(_translate("Incrpatient", "Sexe:"))
        self.label_51.setText(_translate("Incrpatient", "Contact:"))
        self.label_9.setText(_translate("Incrpatient", "Profession:"))
        self.label_11.setText(_translate("Incrpatient", "N° de la CNI:"))
        self.label_10.setText(_translate("Incrpatient", "Nationalité:"))
        self.label_14.setText(_translate("Incrpatient", "Prénom:"))
        self.ann_2.setText(_translate("Incrpatient", "ANNULER"))
        self.save.setText(_translate("Incrpatient", "ENREGISTRER"))

#Fenetre Fiche MEDICALE
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(916, 683)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 141, 111))
        self.label.setStyleSheet("image: url(:/consul_img/img5.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(190, 30, 531, 61))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setWhatsThis("")
        self.label_3.setStyleSheet("border-style:solid;\n""border-width:2px;\n""border-color:black;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(770, 0, 141, 111))
        self.label_4.setStyleSheet("image: url(:/consul_img/img5.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 130, 791, 491))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.groupBox.setStyleSheet("")
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 20, 421, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 19, 401, 126))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(5, 0, 18, 0)
        self.formLayout.setSpacing(3)
        self.formLayout.setObjectName("formLayout")
        self.nomLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nomLabel.setFont(font)
        self.nomLabel.setObjectName("nomLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nomLabel)
        self.nomLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nomLineEdit.setEnabled(False)
        self.nomLineEdit.setObjectName("nomLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nomLineEdit)
        self.prNomsLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.prNomsLabel.setFont(font)
        self.prNomsLabel.setObjectName("prNomsLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.prNomsLabel)
        self.prNomsLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.prNomsLineEdit.setEnabled(False)
        self.prNomsLineEdit.setObjectName("prNomsLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.prNomsLineEdit)
        self.ageLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.ageLabel.setObjectName("ageLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.ageLabel)
        self.ageLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ageLineEdit.setEnabled(False)
        self.ageLineEdit.setObjectName("ageLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ageLineEdit)
        self.poidsLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.poidsLabel.setObjectName("poidsLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.poidsLabel)
        self.poidsLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.poidsLineEdit.setEnabled(False)
        self.poidsLineEdit.setObjectName("poidsLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.poidsLineEdit)
        self.tailleLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.tailleLabel.setObjectName("tailleLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.tailleLabel)
        self.tailleLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.tailleLineEdit.setEnabled(False)
        self.tailleLineEdit.setObjectName("tailleLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.tailleLineEdit)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(450, 20, 321, 161))
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 301, 121))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 13, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.allergieLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.allergieLabel.setFont(font)
        self.allergieLabel.setObjectName("allergieLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.allergieLabel)
        self.allergieComboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.allergieComboBox.setObjectName("allergieComboBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.allergieComboBox)
        self.tempRatureLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.tempRatureLabel.setFont(font)
        self.tempRatureLabel.setObjectName("tempRatureLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tempRatureLabel)
        self.tempRatureLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.tempRatureLineEdit.setObjectName("tempRatureLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tempRatureLineEdit)
        self.mDecinTraitantLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.mDecinTraitantLabel.setFont(font)
        self.mDecinTraitantLabel.setObjectName("mDecinTraitantLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.mDecinTraitantLabel)
        self.serviceLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.serviceLabel.setFont(font)
        self.serviceLabel.setObjectName("serviceLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.serviceLabel)
        self.serviceComboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.serviceComboBox.setObjectName("serviceComboBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.serviceComboBox)
        self.comboBox_medTrait = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.comboBox_medTrait.setObjectName("comboBox_medTrait")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_medTrait)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 200, 421, 221))
        self.groupBox_4.setObjectName("groupBox_4")
        self.textEdit_Observation = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit_Observation.setGeometry(QtCore.QRect(10, 20, 401, 191))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit_Observation.setFont(font)
        self.textEdit_Observation.setObjectName("textEdit_Observation")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(450, 200, 321, 111))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_Symptome = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_Symptome.setGeometry(QtCore.QRect(80, 30, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_Symptome.setFont(font)
        self.lineEdit_Symptome.setStyleSheet("color: red;")
        self.lineEdit_Symptome.setObjectName("lineEdit_Symptome")
        self.commandLinkButtonOrdonance = QtWidgets.QCommandLinkButton(self.groupBox)
        self.commandLinkButtonOrdonance.setGeometry(QtCore.QRect(450, 340, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.commandLinkButtonOrdonance.setFont(font)
        self.commandLinkButtonOrdonance.setDefault(False)
        self.commandLinkButtonOrdonance.setObjectName("commandLinkButtonOrdonance")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(220, 440, 361, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonTerminer = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonTerminer.setFont(font)
        self.pushButtonTerminer.setStyleSheet("")
        self.pushButtonTerminer.setCheckable(False)
        self.pushButtonTerminer.setAutoDefault(True)
        self.pushButtonTerminer.setDefault(True)
        self.pushButtonTerminer.setFlat(False)
        self.pushButtonTerminer.setObjectName("pushButtonTerminer")
        self.verticalLayout.addWidget(self.pushButtonTerminer)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(770, 640, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" text-decoration: underline; color:#aaff00;\">FICHE MEDICALE</span></p></body></html>"))
        self.groupBox.setTitle(_translate("Dialog", "Consultation"))
        self.groupBox_2.setTitle(_translate("Dialog", "Information sur le patient"))
        self.nomLabel.setText(_translate("Dialog", "<html><head/><body><p><span style=\" text-decoration: underline;\">Nom :</span></p></body></html>"))
        self.prNomsLabel.setText(_translate("Dialog", "<html><head/><body><p><span style=\" text-decoration: underline;\">Prénoms :</span></p></body></html>"))
        self.ageLabel.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; text-decoration: underline;\">Age :</span></p></body></html>"))
        self.poidsLabel.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; text-decoration: underline;\">Poids :</span></p></body></html>"))
        self.tailleLabel.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; text-decoration: underline;\">Taille</span></p></body></html>"))
        self.groupBox_3.setTitle(_translate("Dialog", "Informations supplémentaires"))
        self.allergieLabel.setText(_translate("Dialog", "Allergie :"))
        self.tempRatureLabel.setText(_translate("Dialog", "Température:"))
        self.mDecinTraitantLabel.setText(_translate("Dialog", "Médecin Traitant :"))
        self.serviceLabel.setText(_translate("Dialog", "Service :"))
        self.groupBox_4.setTitle(_translate("Dialog", "Observations"))
        self.groupBox_5.setTitle(_translate("Dialog", "Diagnostic"))
        self.label_2.setText(_translate("Dialog", "Symptôme:"))
        self.commandLinkButtonOrdonance.setText(_translate("Dialog", "Prescrire une ordonance médicale"))
        self.pushButtonTerminer.setText(_translate("Dialog", "Terminer la consultation"))
        self.pushButton.setText(_translate("Dialog", "Retour"))

#Fentre Liste
class Ui_liste(object):
    def setupUi(self, liste):
        liste.setObjectName("liste")
        liste.resize(759, 571)
        self.centralwidget = QtWidgets.QWidget(liste)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 20, 671, 531))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        liste.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(liste)
        self.statusbar.setObjectName("statusbar")
        liste.setStatusBar(self.statusbar)

        self.retranslateUi(liste)
        QtCore.QMetaObject.connectSlotsByName(liste)

    def retranslateUi(self, liste):
        _translate = QtCore.QCoreApplication.translate
        liste.setWindowTitle(_translate("liste", "Liste des patients"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("liste", "Date de consultation"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("liste", "Heure"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("liste", "N° de compte"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("liste", "Nom"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("liste", "Prenom(s)"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("liste", "Date de rendez-vous"))

#Fenetre Loading
class Ui_Loging(object):

    def suivant(self):
        open_Ui_Login()
        Loging.hide()

    def setupUi(self, Loging):
        Loging.setObjectName("Loging")
        Loging.resize(628, 468)
        self.centralwidget = QtWidgets.QWidget(Loging)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 601, 401))
        self.groupBox.setStyleSheet("Border-radius: 10px;\n""background-color: rgb(218, 218, 218);")
        self.groupBox.setObjectName("groupBox")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(130, 80, 331, 221))
        self.frame.setStyleSheet("background-color: rgb(127, 127, 127);\n""border-radius: 15px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 40, 111, 51))
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(47, 120, 241, 31))
        self.progressBar.setStyleSheet("border-radius: 5px;\n""background-color: rgb(255, 255, 255);")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        Loging.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Loging)
        self.statusbar.setObjectName("statusbar")
        Loging.setStatusBar(self.statusbar)

        self.retranslateUi(Loging)
        QtCore.QMetaObject.connectSlotsByName(Loging)

    def retranslateUi(self, Loging):
        _translate = QtCore.QCoreApplication.translate
        Loging.setWindowTitle(_translate("Loging", "Hospital"))
        self.groupBox.setTitle(_translate("Loging", "Ouverture de session"))
        self.label.setText(_translate("Loging", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Loading...</span></p></body></html>"))

#Fenetre modifier
class Ui_Modif(object):
    def setupUi(self, Modif):
        Modif.setObjectName("Modif")
        Modif.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Modif)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 50, 651, 501))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QLineEdit{\n""    color: rgb(239, 239, 239);\n""    color: rgb(238, 238, 238);\n""background-color: rgb(188, 188, 188);\n""}")
        self.groupBox.setObjectName("groupBox")
        self.photo = QtWidgets.QLabel(self.groupBox)
        self.photo.setGeometry(QtCore.QRect(540, 10, 101, 101))
        self.photo.setStyleSheet("\n"
        "background-color: rgb(203, 203, 203);")
        self.photo.setObjectName("photo")
        self.prenomClient = QtWidgets.QLineEdit(self.groupBox)
        self.prenomClient.setGeometry(QtCore.QRect(410, 180, 141, 21))
        self.prenomClient.setStyleSheet("border-color:black;\n""border-radius:10px;\n""border-style:solid;\n""border-width:1px;\n""")
        self.prenomClient.setObjectName("prenomClient")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 180, 31, 16))
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(340, 230, 31, 16))
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(330, 180, 47, 13))
        self.label_4.setObjectName("label_4")
        self.nomClient = QtWidgets.QLineEdit(self.groupBox)
        self.nomClient.setGeometry(QtCore.QRect(120, 180, 131, 21))
        self.nomClient.setStyleSheet("border-color:black;\n"
        "border-radius:10px;\n"
        "border-style:solid;\n"
        "border-width:1px;\n"
        "")
        self.nomClient.setText("")
        self.nomClient.setObjectName("nomClient")
        self.tool = QtWidgets.QToolButton(self.groupBox)
        self.tool.setGeometry(QtCore.QRect(620, 120, 25, 19))
        self.tool.setObjectName("tool")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(560, 120, 61, 16))
        self.label_13.setObjectName("label_13")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(310, 270, 91, 16))
        self.label_5.setObjectName("label_5")
        self.date = QtWidgets.QDateEdit(self.groupBox)
        self.date.setGeometry(QtCore.QRect(440, 270, 81, 22))
        self.date.setCalendarPopup(True)
        self.date.setObjectName("date")
        self.prof = QtWidgets.QLineEdit(self.groupBox)
        self.prof.setGeometry(QtCore.QRect(120, 220, 131, 21))
        self.prof.setStyleSheet("border-color:black;\n"
        "border-radius:10px;\n"
        "border-style:solid;\n"
        "border-width:1px;\n"
        "")
        self.prof.setObjectName("prof")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 280, 61, 16))
        self.label_10.setObjectName("label_10")
        self.nation = QtWidgets.QLineEdit(self.groupBox)
        self.nation.setGeometry(QtCore.QRect(120, 280, 131, 21))
        self.nation.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.nation.setStyleSheet("border-color:black;\n"
        "border-radius:10px;\n"
        "border-style:solid;\n"
        "border-width:1px;\n"
        "")
        self.nation.setObjectName("nation")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 220, 61, 16))
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 330, 47, 13))
        self.label_8.setObjectName("label_8")
        self.cni_Client = QtWidgets.QLineEdit(self.groupBox)
        self.cni_Client.setGeometry(QtCore.QRect(420, 310, 131, 21))
        self.cni_Client.setStyleSheet("border-color:black;\n"
        "border-radius:10px;\n"
        "border-style:solid;\n"
        "border-width:1px;\n"
        "")
        self.cni_Client.setObjectName("cni_Client")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(310, 310, 71, 16))
        self.label_11.setObjectName("label_11")
        self.cont = QtWidgets.QLineEdit(self.groupBox)
        self.cont.setGeometry(QtCore.QRect(120, 320, 141, 21))
        self.cont.setStyleSheet("border-color:black;\n"
        "border-radius:10px;\n"
        "border-style:solid;\n"
        "border-width:1px;\n"
        "")
        self.cont.setObjectName("cont")
        self.mail = QtWidgets.QLineEdit(self.groupBox)
        self.mail.setGeometry(QtCore.QRect(120, 360, 131, 21))
        self.mail.setStyleSheet("border-color:black;\n"
        "border-radius:10px;\n"
        "border-style:solid;\n"
        "border-width:1px;\n"
        "")
        self.mail.setObjectName("mail")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(30, 370, 41, 16))
        self.label_12.setObjectName("label_12")
        self.ann = QtWidgets.QPushButton(self.groupBox)
        self.ann.setGeometry(QtCore.QRect(190, 450, 81, 23))
        self.ann.setObjectName("ann")
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setGeometry(QtCore.QRect(310, 450, 20, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.save = QtWidgets.QPushButton(self.groupBox)
        self.save.setGeometry(QtCore.QRect(370, 450, 91, 23))
        self.save.setObjectName("save")
        self.sexe = QtWidgets.QComboBox(self.groupBox)
        self.sexe.setGeometry(QtCore.QRect(420, 230, 131, 22))
        self.sexe.setStyleSheet("border-color:black;\n"
        "border-radius:10px;\n"
        "border-style:solid;\n"
        "border-width:1px;\n"
        "")
        self.sexe.setObjectName("sexe")
        self.sexe.addItem("")
        self.sexe.setItemText(0, "")
        self.sexe.addItem("")
        self.sexe.addItem("")
        self.sexe_3 = QtWidgets.QComboBox(self.groupBox)
        self.sexe_3.setGeometry(QtCore.QRect(430, 370, 131, 22))
        self.sexe_3.setStyleSheet("border-color:black;\n"
        "border-radius:10px;\n"
        "border-style:solid;\n"
        "border-width:1px;\n"
        "")
        self.sexe_3.setObjectName("sexe_3")
        self.sexe_3.addItem("")
        self.sexe_3.setItemText(0, "")
        self.sexe_3.addItem("")
        self.sexe_3.addItem("")
        self.sexe_3.addItem("")
        self.sexe_3.addItem("")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(340, 370, 61, 16))
        self.label.setObjectName("label")
        Modif.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Modif)
        self.statusbar.setObjectName("statusbar")
        Modif.setStatusBar(self.statusbar)

        self.retranslateUi(Modif)
        QtCore.QMetaObject.connectSlotsByName(Modif)

    def retranslateUi(self, Modif):
        _translate = QtCore.QCoreApplication.translate
        Modif.setWindowTitle(_translate("Modif", "MainWindow"))
        self.groupBox.setTitle(_translate("Modif", "MODIFICATION DE COMPTE"))
        self.photo.setText(_translate("Modif", "<html><head/><body><p align=\"center\">photo</p></body></html>"))
        self.label_3.setText(_translate("Modif", "Nom:"))
        self.label_7.setText(_translate("Modif", "Sexe:"))
        self.label_4.setText(_translate("Modif", "Prénom:"))
        self.tool.setText(_translate("Modif", "..."))
        self.label_13.setText(_translate("Modif", "<html><head/><body><p><span style=\" font-weight:600;\">Parcourir:</span></p></body></html>"))
        self.label_5.setText(_translate("Modif", "Date de naissance:"))
        self.label_10.setText(_translate("Modif", "Nationalité:"))
        self.nation.setPlaceholderText(_translate("Modif", "ivoirienne"))
        self.label_9.setText(_translate("Modif", "Profession:"))
        self.label_8.setText(_translate("Modif", "Contact:"))
        self.cni_Client.setPlaceholderText(_translate("Modif", "CI"))
        self.label_11.setText(_translate("Modif", "N° de la CNI:"))
        self.cont.setPlaceholderText(_translate("Modif", "+225"))
        self.label_12.setText(_translate("Modif", "E-mail:"))
        self.ann.setText(_translate("Modif", "ANNULER"))
        self.save.setText(_translate("Modif", "ENREGISTRER"))
        self.sexe.setItemText(1, _translate("Modif", "HOMME"))
        self.sexe.setItemText(2, _translate("Modif", "FEMME"))
        self.sexe_3.setItemText(1, _translate("Modif", "axa"))
        self.sexe_3.setItemText(2, _translate("Modif", "assurace"))
        self.sexe_3.setItemText(3, _translate("Modif", "mugefci"))
        self.sexe_3.setItemText(4, _translate("Modif", "dangereux "))
        self.label.setText(_translate("Modif", "assurance:"))

#Fenetre Login
class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(628, 553)
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 601, 511))
        self.groupBox.setStyleSheet("Border-radius: 10px;\n"
        "background-color: rgb(218, 218, 218);")
        self.groupBox.setObjectName("groupBox")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(130, 110, 331, 291))
        self.frame.setStyleSheet("background-color: rgb(127, 127, 127);\n"
        "border-radius: 15px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.username_log = QtWidgets.QLineEdit(self.frame)
        self.username_log.setGeometry(QtCore.QRect(100, 80, 211, 21))
        self.username_log.setStyleSheet("background-color: rgb(225, 225, 225);\n"
        "border-radius: 5px;")
        self.username_log.setObjectName("username_log")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 71, 16))
        self.label_3.setObjectName("label_3")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setGeometry(QtCore.QRect(100, 140, 211, 21))
        self.password.setStyleSheet("background-color: rgb(225, 225, 225);\n"
        "border-radius: 5px;")
        self.password.setObjectName("password")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 10, 111, 51))
        self.label.setObjectName("label")
        self.connexion = QtWidgets.QPushButton(self.frame)
        self.connexion.setGeometry(QtCore.QRect(100, 210, 121, 23))
        self.connexion.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
        "background-color: rgb(170, 255, 255);\n"
        "border-radius:10px;")
        self.connexion.setObjectName("connexion")
        Login.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Hospital"))
        self.groupBox.setTitle(_translate("Login", "Ouverture de session"))
        self.label_2.setText(_translate("Login", "<html><head/><body><p><span style=\" font-weight:600;\">USERNAME :</span></p></body></html>"))
        self.label_3.setText(_translate("Login", "<html><head/><body><p><span style=\" font-weight:600;\">PASSWORD :</span></p></body></html>"))
        self.label.setText(_translate("Login", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Login...</span></p></body></html>"))
        self.connexion.setToolTip(_translate("Login", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">CONNECTION</span></p></body></html>"))
        self.connexion.setWhatsThis(_translate("Login", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">CONNECTION</span></p><p align=\"center\"><br/></p></body></html>"))
        self.connexion.setText(_translate("Login", "CONNECTION"))

#Fenetre SUPPRIMER
class Ui_Suppression(object):
    def setupUi(self, Suppression):
        Suppression.setObjectName("Suppression")
        Suppression.resize(659, 570)
        self.centralwidget = QtWidgets.QWidget(Suppression)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 90, 601, 361))
        self.groupBox.setStyleSheet("Border-radius: 10px;\n"
        "background-color: rgb(218, 218, 218);")
        self.groupBox.setObjectName("groupBox")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(130, 80, 331, 201))
        self.frame.setStyleSheet("background-color: rgb(127, 127, 127);\n"
        "border-radius: 15px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 81, 20))
        self.label_3.setObjectName("label_3")
        self.no_compte_sup = QtWidgets.QLineEdit(self.frame)
        self.no_compte_sup.setGeometry(QtCore.QRect(100, 80, 211, 21))
        self.no_compte_sup.setStyleSheet("background-color: rgb(225, 225, 225);\n"
        "border-radius: 5px;")
        self.no_compte_sup.setObjectName("no_compte_sup")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 10, 281, 41))
        self.label.setObjectName("label")
        self.bouton_sup = QtWidgets.QPushButton(self.frame)
        self.bouton_sup.setGeometry(QtCore.QRect(30, 140, 121, 23))
        self.bouton_sup.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
        "background-color: rgb(170, 255, 255);\n"
        "border-radius:10px;")
        self.bouton_sup.setObjectName("bouton_sup")
        self.annuler_sup = QtWidgets.QPushButton(self.frame)
        self.annuler_sup.setGeometry(QtCore.QRect(180, 140, 121, 23))
        self.annuler_sup.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
        "background-color: rgb(170, 255, 255);\n"
        "border-radius:10px;")
        self.annuler_sup.setObjectName("annuler_sup")
        Suppression.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Suppression)
        self.statusbar.setObjectName("statusbar")
        Suppression.setStatusBar(self.statusbar)

        self.retranslateUi(Suppression)
        QtCore.QMetaObject.connectSlotsByName(Suppression)

    def retranslateUi(self, Suppression):
        _translate = QtCore.QCoreApplication.translate
        Suppression.setWindowTitle(_translate("Suppression", "MainWindow"))
        self.groupBox.setTitle(_translate("Suppression", "Suppression"))
        self.label_3.setText(_translate("Suppression", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">N° de compte:</span></p></body></html>"))
        self.label.setText(_translate("Suppression", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Suppression du patient...</span></p></body></html>"))
        self.bouton_sup.setToolTip(_translate("Suppression", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">CONNECTION</span></p></body></html>"))
        self.bouton_sup.setWhatsThis(_translate("Suppression", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">CONNECTION</span></p><p align=\"center\"><br/></p></body></html>"))
        self.bouton_sup.setText(_translate("Suppression", "SUPPRIMER"))
        self.annuler_sup.setToolTip(_translate("Suppression", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">CONNECTION</span></p></body></html>"))
        self.annuler_sup.setWhatsThis(_translate("Suppression", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">CONNECTION</span></p><p align=\"center\"><br/></p></body></html>"))
        self.annuler_sup.setText(_translate("Suppression", "ANNULER"))


#Classes-----------------------------------------Classes

#Launching
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    open_Ui_Loging()
    sys.exit(app.exec_())
